spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.101.132:3306/wangpan?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.101.132
    port: 5672
    virtual-host: /
    username: root
    password: 123456
  elasticsearch:
    uris: 192.168.101.132:9200

  data:
    redis:
      host: 192.168.101.132
      port: 6379
  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-4o-mini
    stabilityai:
      api-key: test
    ollama:
      base-url: http://localhost:11434










mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true      # 下划线转成驼峰
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0


gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10


server:
  port: 8888

minio:
  endpoint: http://192.168.101.132:9000
  accessKey: admin
  secretKey: admin123

